# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NickelDemo' do
   pod 'NickelSwift', :git => 'https://github.com/riana/NickelSwift.git'
end

target 'NickelDemoTests' do

end
